version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<database>
      - PORT=5000
      - DEEPSEEK_API_KEY=your_deepseek_api_key
    restart: unless-stopped