name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test || true  # Continue even if tests fail (remove "|| true" if you want to enforce passing tests)

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.key
        chmod 600 ~/.ssh/ec2.key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        rsync -avz -e "ssh -i ~/.ssh/ec2.key" --exclude=node_modules --exclude=.git --delete ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/portfolio-backend/

    - name: Restart Services
      run: |
        ssh -i ~/.ssh/ec2.key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          cd ~
          export MONGODB_URI="${{ secrets.MONGODB_URI }}"
          export DEEPSEEK_API_KEY="${{ secrets.DEEPSEEK_API_KEY }}"
          docker-compose down
          docker-compose up -d --build
        '

    - name: Verify Deployment
      run: |
        echo "Waiting for services to start..."
        sleep 10
        curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.WEBSITE_DOMAIN }}/api/health || echo "Health check endpoint not reachable"